development:
  adapter: postgresql
  encoding: unicode
  database: light_countdown_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: light_countdown_test
  pool: 5
  username:
  password:
